Deniz Uzun
wellesley-bisc195/NeedlemanWunsch pull request #2
Opened 2021-06-15 20:01 UTC by denizeu

2021-06-19 18:59 UTC, kescobo requested changes

2021-06-19 18:59 UTC, kescobo commented on src/needleman_wunch.jl
> +            return -1
Looks like and end is missing

2021-06-19 21:09 UTC, denizeu commented
Do you have any advice on how to add the match and mismatch within the code? Did I define it properly in the function? @kescobo

2021-06-21 18:55 UTC, kescobo requested changes
I see you've been trying a lot of stuff, but may be going around in circles a bit. Let me know if we can hop on a call today or tomorrow.

2021-06-21 18:55 UTC, kescobo commented on src/needleman_wunch.jl
> +function nwscore(base1::Char, base2::Char; match, mismatch)
The purpose of `match` and `mismatch` here is to provide an alternative scoring system. So I think you want something like

```
function wscore(base1::Char, base2::Char; match=1, mismatch=-1)
    if base1 == base2
        return match
    end
    # ... etc
end
```

2021-06-21 20:01 UTC, denizeu commented
> I see you've been trying a lot of stuff, but may be going around in circles a bit. Let me know if we can hop on a call today or tomorrow.

A zoom call tomorrow would be super helpful, thank you! @kescobo

2021-06-28 17:11 UTC, kescobo commented
Not sure why the automated tests are failing to run here - let me know if you think you're done and I'll run them locally

2021-06-28 18:49 UTC, denizeu commented
@kescobo I am definitely done with lab3 but not with lab4... it might be because I am continuing to work on lab4 through this same file? Anika and I decided that would be the best way to still have the old needleman_wunch to work on for lab4, maybe there is a better way?

2021-06-28 19:20 UTC, denizeu commented
@kescobo I'm actually a bit more confused now. I did lab 6 with Emily which should be done, and I also finished up lab 3. I should only be missing/working on lab 4, I think the locations are unclear for me at the moment. This branch should be the needleman_wunch uncorrected file with only lab 3 and lab 4 right?

2021-07-02 18:57 UTC, closed without merging

2021-07-05 18:21 UTC, kescobo commented
Lab 3 complete as of https://github.com/wellesley-bisc195/AlignmentAlgorithms/pull/2/commits/3f4fe7fde2ed620d72c444dd71d8eb3a6a4f4069